apiVersion: extensions/v1beta1
kind: "Deployment"
metadata:
  name: #{DOCKER_IMAGE}-#{VERSION}
  namespace: #{APP_NAME}
  labels:
    app: #{DOCKER_IMAGE}
    release: #{DOCKER_IMAGE}-v#{VERSION}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{DOCKER_IMAGE}
      release: #{DOCKER_IMAGE}-v#{VERSION}
  template:
    metadata:
      labels:
        app: #{DOCKER_IMAGE}
        release: #{DOCKER_IMAGE}-v#{VERSION}
    spec:
      containers:
      - name: #{DOCKER_IMAGE}
        image: #{DOCKER_HOST}/#{DOCKER_IMAGE}:#{VERSION}
        env:
        - name: DB_HOST
          value: "ds029837.mlab.com"
        - name: DB_PORT
          value: "29837"
        - name: DB_NAME
          value: "lazy_load_dev"
        - name: DB_USER
          value: "user"
        - name: DB_PASS
          value: "tnsPass0"
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"  