apiVersion: v1
kind: Service
metadata:
  name: #{DOCKER_IMAGE}-service
  namespace: #{APP_NAME}
  labels:
    app: #{DOCKER_IMAGE}
    env: #{DEPLOYMENT}
spec:
  type: ClusterIP
  selector:
    release: v#{VERSION}
  ports:
    - port: 9000
      targetPort: 9000